### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by HackerBaloo** [seanfisher/passport-microsoft#1]
I tried the example, did run "npm install", but then I get a too new version of express, so I get an error about app.configure doesn't exist. So I changed express to 3.21.2.
Which versions of the npm packages is it known to work with?
After downgrading express I was able to start a login, but it failed with a "CompactToken parsing failed with error code: 80049217"

**Comment by seanfisher** [comment]
I updated the `package.json` to include the functioning version of `express` and other dependencies. Thanks for opening the issue.
