### ISSUE TITLE
Force account selection

### ISSUE THREAD

**Issue by aks-71** [seanfisher/passport-microsoft#13]
Is there a way to force account selection in case user has multiple accounts? Currently it directly signs in with a account without asking

**Comment by lauming1111** [comment]
@aks-71  need to update the file in node_modules manually, refer to https://github.com/seanfisher/passport-microsoft/pull/8/files

and add `prompt: 'select_account'` in your code (I am using MS Oauth, https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow)

**Comment by seanfisher** [comment]
Released in 1.0.0. Take a look at [this sample app line](https://github.com/seanfisher/passport-microsoft/blob/101bdd953877d4a7d6e2ce76bf6b89c282deec4c/example/login/app.js#L94) to see where to specify this option.
