### ISSUE TITLE
failureRedirect not working 

### ISSUE THREAD

**Issue by priyatham1188** [seanfisher/passport-microsoft#22]
Hello,

In my application, I'm using single-tenant AAD account where if I try to login with the other domain it's not redirecting to failureRedirect instead it's sitting on the Microsoft page itself and showing the error as shown below.Can anyone please help me on this issue?

User account 'xxxx@gmail.com' from identity provider 'live.com' does not exist in tenant 'xxxxxxx' and cannot access the application '{id}'(Name) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by seanfisher** [comment]
Cleaning up old issues. @priyatham1188 - please re-open if you still need help. Sounds like this issue is a configuration issue with how you set up your tenant application and/or users.
