### ISSUE TITLE
Session state creating issue while redirecting to redirect URI

### ISSUE THREAD

**Issue by tushaar9027** [seanfisher/passport-microsoft#24]
I am getting while it is redirecting in azure app service after it goes to authorize endpoint and send the authorization code to redirect uri. I get the below error

https://<appname>.azurewebsites.net/auth/redirect?code=<Authorization_Code>&session_state=18b77656-7bb0-45e7-a678-5944ec526564

After i remove the session state manually and try it works fine . 

Can someone help me understand why this is happening and how to correct this. (Like skip session state while sending)

**Comment by dtrikannad** [comment]
Hi Tushaar, did you ever figure this out?

**Comment by seanfisher** [comment]
@tushaar9027 - Could you share more details to help with troubleshooting? An error message, or a screen shot? How are you configuring the MicrosoftStrategy instance? What versions of the libraries are you using?
