### ISSUE TITLE
Unable to access the dynamics CRM contacts

### ISSUE THREAD

**Issue by Raman99444** [seanfisher/passport-microsoft#28]
I used this package to authenticate the dynamics CRM. I have used the below code

```
passport.use(new MicrosoftStrategy({
  clientID: process.env.MICROSOFT_CLIENT_ID,
  clientSecret: process.env.MICROSOFT_CLIENT_SECRET,
  callbackURL: process.env.MICROSOFT_REDIRECT_URI,
  tenant: process.env.MICROSOFT_TENANT_ID,
  passReqToCallback: true,
  scope: ['openid,user.read,offline_access,profile,email,Contacts.Read'],
  scopeSeparator: ','
},
async (req, accessToken, refreshToken, expires_in, profile, done) => {
   done(null, profile)
}))
```

But, while using this code I faced the issue like below,

```
microsoft/callback?error=invalid_client&error_description=AADSTS650053%3a+The+application+%27TestApp-App%27+asked+for+scope+%27openid%2cuser.read%2coffline_access%2cprofile%2cemail%2cContacts.Read%27+that+doesn%27t+exist+on+the+resource+%2700000003-0000-0000-c000-000000000000%27.+Contact+the+app+vendor.%0d%0aTrace+ID%3a+611c5ab0-4da5-4dc9-afe7-8b47d83a7f00%0d%0aCorrelation+ID%3a+4354bc5e-28e6-495e-86b0-881723d2589d%0d%0aTimestamp%3a+2023-07-06+17%3a37%3a31Z
```

I followed the below document to create the client and secret ID

https://learn.microsoft.com/en-us/power-apps/developer/data-platform/walkthrough-register-app-azure-active-directory

It would be good someone help on this

**Comment by Raman99444** [comment]
I would like to add one more point: I can create the access and secret tokens even if I haven't configured the scope.

**Comment by seanfisher** [comment]
Unfortunately I'm not sure of the scopes needed for Dynamics, and not having a Dynamics instance myself, I can't try to reproduce. I'm sure you already have done this, but I would double check your application configured permissions and make sure you're requesting the right type of permissions (application vs. delegated) for what you're trying to accomplish.
