### ISSUE TITLE
Error occurs on example: TokenError: AADSTS70012: Non-retryable error has occurred. 

### ISSUE THREAD

**Issue by vasilevach** [seanfisher/passport-microsoft#3]
Hi there!

It seems that the Azure API has been updated of some sort and the library stopped working since January. Login causes error: _TokenError: AADSTS70012: Non-retryable error has occurred_ . Could you please take a peek, or point up to directions were we can find in the documentation what is wrong with this API?

Thank you so much!

**Comment by seanfisher** [comment]
Thanks for opening the issue. Are you still seeing this? I haven't been able to reproduce and it sounds like some sort of intermittent error with Azure (see also https://docs.microsoft.com/answers/questions/6541/azure-active-directory-aadsts90092-non-retryable-e.html). 

If you have some reproducible steps or some non-working code, feel free to re-open.
