### ISSUE TITLE
Personal account support

### ISSUE THREAD

**Issue by pnmcosta** [seanfisher/passport-microsoft#4]
Hi there,

I'm having an issue with trying to login with personal live.com accounts instead of Office 365.

The oauth process is essentially the same, and the live.com endpoints should work for both.

And it is, except for the only problem I'm having with the email, it does not appear to be populating the `profile.emails` with a proper value for the email (even though the array has got one record) the value is always undefined.

The problem appears to be with the personal accounts not populating the `mail` property, as expected by the strategy here: 

But instead return the `userPrincipalName`, see a debug session below with the `_json` property.
![image](https://user-images.githubusercontent.com/550684/59099827-33a43580-891c-11e9-98fc-d55fd3a6da60.png)

I can obviously get it from the `_json`, but I think it would make more sense to have the strategy support it?

I can do the change on a fork and PR it if you'd like?

Cheers,
P.

**Comment by pnmcosta** [comment]
Sorry, it's not clear from the screenshot, as I blurred it, but `userPrincipalName` does contain the email address as expected :)

**Comment by nhu** [comment]
Hi,

since I had the same problem today I quickly added the userPrincipalName as fallback value for the mail. 
So this should be backwards compatible and we have at least a value if the "mail" property is empty.
I've added a PR.

**Comment by seanfisher** [comment]
Thanks for opening the issue, and thanks @nhu for the fix. 

The fix is now released in version v0.1.0.
