### ISSUE TITLE
OAuth2 Authorization code was already redeemed 

### ISSUE THREAD

**Issue by paulo-gyant** [seanfisher/passport-microsoft#9]
First of all, thank you for your work!

I have been using `passport-microsoft` and it has been working great.

Although, I have some users reporting a strange problem while trying to login with their Microsoft/Azure Active Directory account.

Here is a print of the error:

![image](https://user-images.githubusercontent.com/66627275/101001057-8df47580-3556-11eb-8b06-dd991b89e256.png)

Do you have an idea of what might be causing this?

**Comment by seanfisher** [comment]
Have not seen that one before. Is it still happening?
